---
knit: "bookdown::preview_chapter"
---

# Technical Podcasts

These podcasts are aimed at a more technical audience.

## Becoming a Data Scientist

A biweekly interview with a data scientist or someone on their way to becoming a data scientist.

* [\@BecomingDataSci](https://twitter.com/BecomingDataSci)
* [Website](http://www.becomingadatascientist.com/category/podcast/)
* [Stitcher](http://www.stitcher.com/podcast/becoming-a-data-scientist-podcast)
* [RSS](https://www.becomingadatascientist.com/feed/podcast)

## Concerning AI 

A show about AI. 

* [Website](https://concerning.ai/)
* [iTunes](https://itunes.apple.com/us/podcast/concerning-ai-existential-risk-from-artificial-intelligence/id1038719211?mt=2)

## DataFramed

DataCamp’s official podcast. 

* [Website](https://www.datacamp.com/community/podcast)
* [iTunes](https://itunes.apple.com/au/podcast/dataframed/id1336150688)
* [GooglePlay Music](https://playmusic.app.goo.gl/?ibi=com.google.PlayMusic&isi=691797987&ius=googleplaymusic&apn=com.google.android.music&link=https://play.google.com/music/m/Idltnsiq2bvzpfzn5tni3iixyta?t%3DDataFramed%26pcampaignid%3DMKT-na-all-co-pr-mu-pod-16)
* [SoundCloud](https://soundcloud.com/dataframed)

## Data Science at home

Podcast about datascience and machine learning, focused on entreprise applications.

* [Website](http://podcast.datascienceathome.com/)
* [iTunes](https://itunes.apple.com/us/podcast/data-science-at-home/id1069871378?mt=2)

## Data Stories

[Data Stories](http://datastori.es/) is a podcast on data visualisation by 
Enrico Bertini and Moritz Stefaner.

 * [\@datastories](https://twitter.com/datastories)
 * [Website](http://datastori.es/)

## Data Skeptic

Data Skeptic is your source for a perspective of scientific skepticism on topics in
statistics, machine learning, big data, artificial intelligence, and data science. Our
weekly podcast and blog bring you stories and tutorials to help understand our
data-driven world.

  * [\@DataSkeptic](https://twitter.com/DataSkeptic)
  * [Website](https://dataskeptic.com/)

## Learning Machines 101

A podcast focused on introduction to machine learning.

* [Website](http://www.learningmachines101.com/)
* [iTunes](https://itunes.apple.com/us/podcast/learning-machines-101/id892779679?mt=2)

## Linear Digression

Linear Digressions is a podcast about Machine Learning and Data Science

 * [\@LinDigressions](https://twitter.com/LinDigressions)

## Not so Standard Deviations

A data science podcast by Roger Peng [\@rdpeng](https://twitter.com/rdpend) and
Hilary Parker [\@hspter](https://twitter.com/hspter) who talk about the latest in
data science and data analysis in academia and industry. They talk a lot about R and
common problems in the life of a data scientist.

 * [\@SSDeviations](https://twitter.com/nssdeviations)
 * [iTunes](https://itunes.apple.com/us/podcast/not-so-standard-deviations/id1040614570?mt=2)

## O'Reilly Data Show

The O'Reilly Data Show Podcast explores the opportunities and techniques driving big data and data science.

 * [Website](https://www.oreilly.com/topics/oreilly-data-show-podcast)
 * [itunes](https://itunes.apple.com/us/podcast/oreilly-data-show/id944929220)
 * [Stitcher](http://www.stitcher.com/podcast/oreilly-media-2/the-oreilly-data-show-podcast?refid=stpr)
 * [SoundCloud](https://soundcloud.com/oreilly-radar/sets/the-oreilly-data-show-podcast)
 * [RSS](http://feeds.podtrac.com/IOJSwQcdEBcg)

## Partially Derivative 

 * [\@partiallyd](https://twitter.com/partiallyd)
 * [Website](http://partiallyderivative.com/)


## The R Podcast

As the name suggests, this [podcast](https://r-podcast.org/) is focused on R.

 * [\@thercast](https://twitter.com/thercast)


## Talking Machines

A podcast talking about machine learning. The hosts Katherine Gorman and Neil Lawrence bring clear conversations with experts in the field, insightful discussions of industry topics, and useful answers to questions.

* [Website](http://www.thetalkingmachines.com/)
* [\TlkngMchns](https://twitter.com/TlkngMchns)
* [Soundcloud](https://soundcloud.com/talkingmachines)
* [RSS](http://www.thetalkingmachines.com/blog/?format=RSS)
* [iTunes](https://itunes.apple.com/us/podcast/episodes-talking-machines/id955198749?mt=2)

 
## Data Science Imposters

 * [\@dsimposters](https://twitter.com/dsimposters)
 * [Website](https://datascienceimposters.com/)
 * [Facebook](https://www.facebook.com/dsimposters)
 
 

